#import tkinter as tk
#def display_message():
#    name = entry_name.get()
#    age = entry_age.get()
#    welcome_label.config(text=f"Welcome, {name}! You are {age} years old")
#window = tk.Tk()
#window.title("Welcome Message App-1")
#label_name = tk.Label(window, text="Enter your name:")
#entry_name = tk.Entry(window)
#label_age = tk.Label(window, text = 'Enter your Age:')
#entry_age = tk.Entry(window)
#welcome_button = tk.Button(window, text="Show Welcome Message", command=display_message)
#label_name.pack()
#entry_name.pack()
#label_age.pack()
#entry_age.pack()
#welcome_button.pack()
#welcome_label = tk.Label(window, text="")
#welcome_label.pack()
#window.mainloop()
import tkinter as tk
def calculate_total():
    number1 = float(entry_numb1.get())
    number2 = float(entry_numb2.get())
    number3 = float(entry_numb3.get())
    result = number1 + number2 + number3
    result_label.config(text = f'Total Marks: {result}')
    average = (number1 + number2 + number3)/3
    average_label.config(text = f'Average Marks: {average}')
window = tk.Tk()
window.title('Student Mark Calculator')
label_numb1 = tk.Label(window, text= 'Enter Test Mark 1:')
entry_numb1 = tk.Entry(window)
label_numb2 = tk.Label(window, text = 'Enter Test Mark 2:')
entry_numb2 = tk.Entry(window)
label_numb3 = tk.Label(window, text = 'Enter Test 3 Mark:')
entry_numb3 = tk.Entry(window)
calculate_btn = tk.Button(window, text = 'Calculate Total and Average', command = calculate_total)
label_numb1.pack()
entry_numb1.pack()
label_numb2.pack()
entry_numb2.pack()
label_numb3.pack()
entry_numb3.pack()
calculate_btn.pack()
result_label = tk.Label(window, text='')
result_label.pack()
average_label = tk.Label(window)
average_label.pack()
window.mainloop()

